// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAavQkV3PxI7Ixpfe3qCfu5XhxRbMdXdgg',
    appId: '1:613550733005:web:825e3722f03da6d8d7db84',
    messagingSenderId: '613550733005',
    projectId: 'hello-b441f',
    authDomain: 'hello-b441f.firebaseapp.com',
    storageBucket: 'hello-b441f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXjsCvpb7PI78oDZoBKhjp7OmX_iCiomo',
    appId: '1:613550733005:android:1e428c1096b57943d7db84',
    messagingSenderId: '613550733005',
    projectId: 'hello-b441f',
    storageBucket: 'hello-b441f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYWLlrOnjMpxMiaw3ioItYFcR15H728qg',
    appId: '1:613550733005:ios:5161b18f2dc15207d7db84',
    messagingSenderId: '613550733005',
    projectId: 'hello-b441f',
    storageBucket: 'hello-b441f.firebasestorage.app',
    iosBundleId: 'com.example.complaintApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYWLlrOnjMpxMiaw3ioItYFcR15H728qg',
    appId: '1:613550733005:ios:5161b18f2dc15207d7db84',
    messagingSenderId: '613550733005',
    projectId: 'hello-b441f',
    storageBucket: 'hello-b441f.firebasestorage.app',
    iosBundleId: 'com.example.complaintApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAavQkV3PxI7Ixpfe3qCfu5XhxRbMdXdgg',
    appId: '1:613550733005:web:825e3722f03da6d8d7db84',
    messagingSenderId: '613550733005',
    projectId: 'hello-b441f',
    authDomain: 'hello-b441f.firebaseapp.com',
    storageBucket: 'hello-b441f.firebasestorage.app',
  );
}
